# Generated by Django 4.2.5 on 2023-11-13 02:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0016_alter_blogcategory_blogresume_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="projectComplete",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="projectResume",
            field=models.TextField(blank=True),
        ),
    ]
